import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // Material Design 3 / Stitch color system
        "primary": "#001732",
        "primary-darker": "#081b31",
        "primary-container": "#0d2c4f",
        "on-primary": "#ffffff",
        "on-primary-container": "#7a94bd",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#adc8f3",
        "on-primary-fixed": "#001c3a",
        "on-primary-fixed-variant": "#2d486c",
        "inverse-primary": "#adc8f3",
        "secondary": "#006493",
        "secondary-container": "#58bcfd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004a6e",
        "secondary-fixed": "#cae6ff",
        "secondary-fixed-dim": "#8ccdff",
        "on-secondary-fixed": "#001e30",
        "on-secondary-fixed-variant": "#004b70",
        "tertiary": "#001929",
        "tertiary-container": "#002f47",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#2a9bda",
        "tertiary-fixed": "#c9e6ff",
        "tertiary-fixed-dim": "#8bceff",
        "on-tertiary-fixed": "#001e2f",
        "on-tertiary-fixed-variant": "#004b6f",
        "surface": "#faf9fc",
        "surface-dim": "#dad9dd",
        "surface-bright": "#faf9fc",
        "surface-variant": "#e3e2e5",
        "surface-tint": "#456085",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#43474e",
        "inverse-surface": "#2f3033",
        "inverse-on-surface": "#f1f0f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f6",
        "surface-container": "#eeedf1",
        "surface-container-high": "#e9e7eb",
        "surface-container-highest": "#e3e2e5",
        "outline": "#74777f",
        "outline-variant": "#c4c6cf",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1e",
        // Home / accent colors
        "accent-blue": "#2095D4",
        "accent-blue-alt": "#1B94D2",
        "saldivia-blue": "#2095D4",
        "saldivia-accent": "#1B94D2",
        "industrial-charcoal": "#121212",
        "industrial-steel": "#2C2C2E",
        "metallic-silver": "#E5E7EB",
        "background-light": "#FFFFFF",
        "background-dark": "#0A141D",
      },
      fontFamily: {
        display: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        tech: ["var(--font-orbitron)", "Orbitron", "sans-serif"],
        mono: ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        outfit: ["var(--font-outfit)", "Outfit", "sans-serif"],
        headline: ["var(--font-plus-jakarta)", "'Plus Jakarta Sans'", "sans-serif"],
        label: ["var(--font-plus-jakarta)", "'Plus Jakarta Sans'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
